version: '3'
services:
  app:
    container_name: git_deploy_app
    build:
      context: ./
      dockerfile: ./app.dockerfile
    working_dir: /var/home
    environment:
     - DEPLOY_TOKEN=${DEPLOY_TOKEN}
     - REMOTE_REPOSITORY=${REMOTE_REPOSITORY}
     - REPO_DIR=${REPO_DIR}
     - REPO_BRANCH=${REPO_BRANCH}
     - LOGFILE=${LOGFILE}
     - GIT_PATH=${GIT_PATH}
     - AFTER_PULL_COMMAND=${AFTER_PULL_COMMAND}
    volumes:
      - ../:/var/www
      - ../logs:/var/www/logs
      - ${REPO_DIR}:/var/repo
      - ../keys/${PRIVATE_KEY}:/var/home/.ssh/id_rsa
  web:
    container_name: git_deploy_web
    build:
      context: ./
      dockerfile: ./web.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
    ports:
      - 8081:80
